// MESSAGES ACTIONS TYPES
export const ON_MESSAGES_VALUE_CHANGE = 'ON_MESSAGES_VALUE_CHANGE';
export const ON_MESSAGES_READING = 'ON_MESSAGES_READING';
export const ON_MESSAGES_READ = 'ON_MESSAGES_READ';

// USER ACTIONS TYPES
export const USER_GET_PENDING = 'USER_GET_PENDING';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';
export const GIVEUSER = 'user/GIVEUSER';

// ALL USERS ACTIONS TYPES
export const ALL_USERS_GET_PENDING = 'ALL_USERS_GET_PENDING';
export const ALL_USERS_GET_SUCCESS = 'ALL_USERS_GET_SUCCESS';
export const ALL_USERS_GET_FAILURE = 'ALL_USERS_GET_FAILURE';

// Question List Types
export const QUESTIONLIST_GET_PENDING = 'questionlist/QUESTIONLIST_GET_PENDING';
export const QUESTIONLIST_GET_SUCCESS = 'questionlist/QUESTIONLIST_GET_SUCCESS';
export const QUESTIONLIST_GET_ERROR = 'questionlist/QUESTIONLIST_GET_ERROR';
export const QUESTIONLIST_DELETE = 'questionlist/QUESTIONLIST_DELETE'

// SESSION ACTIONS TYPES
export const SETLIVE = 'session/setlive';
export const SESSION_GET_PENDING = 'SESSION_GET_PENDING';
export const SESSION_GET_SUCCESS = 'SESSION_GET_SUCCESS';
export const SESSION_GET_FAILURE = 'SESSION_GET_FAILURE';
// MY_SESSION ACTIONS TYPES
export const MY_SETLIVE = 'mySession/setlive';
export const MY_SESSION_GET_PENDING = 'MY_SESSION_GET_PENDING';
export const MY_SESSION_GET_SUCCESS = 'MY_SESSION_GET_SUCCESS';
export const MY_SESSION_GET_FAILURE = 'MY_SESSION_GET_FAILURE';

// Entered Session Types
export const ENTEREDSESSION_GET_PENDING = 'enteredSession/ENTEREDSESSION_GET_PENDING';
export const ENTEREDSESSION_GET_SUCCESS = 'enteredSession/ENTEREDSESSION_GET_SUCCESS';
export const ENTEREDSESSION_GET_ERROR = 'enteredSession/ENTEREDSESSION_GET_ERROR';
export const ENTEREDSESSION_DELETE = 'enteredSession/ENTEREDSESSION_DELETE'