// MESSAGES ACTIONS TYPES
export const ON_MESSAGES_VALUE_CHANGE = 'ON_MESSAGES_VALUE_CHANGE';
export const ON_MESSAGES_READING = 'ON_MESSAGES_READING';
export const ON_MESSAGES_READ = 'ON_MESSAGES_READ';

