export const sessionDummy = [
    {
        roomId : "room1",
        roomName : "오늘 앨범 나왔어요",
        roomSubName : "많이 들어주세요 ^^",
        hostName : "IU",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-25",
        reserveMax : 10,
        reserveUsers : ["hu"],
        isLive : true,
        imageLink : "/static/live_IU.png",
        channelNum : 12345,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room2",
        roomName : "live_room2",
        hostName : "kyo",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["hu"],
        isLive : true,
        imageLink : "/static/livetest.png",
        channelNum : 0,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room3",
        roomName : "live_room3",
        hostName : "kyo",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["hu"],
        isLive : true,
        channelNum : 0,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room4",
        roomName : "live_room4",
        hostName : "kyo",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["hu"],
        isLive : true,
        channelNum : 0,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room4",
        roomName : "live_room5",
        hostName : "seong",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["seo", "kyo"],
        isLive : true,
        channelNum : 0,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room5",
        roomName : "live_room6",
        hostName : "seong",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["seo"],
        isLive : true,
        channelNum : 0,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room6",
        roomName : "live_room7",
        hostName : "seong",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["seo", "kyo"],
        isLive : true,
        channelNum : 0,
        liveUsers : ["seo", "kyo"],
    },
    {
        roomId : "room7",
        roomName : "reserve_room1",
        hostName : "kyo",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 10,
        reserveUsers : ["kyo", "seo", "","","","",""],
        isLive : false,
        channelNum : 0,
        liveUsers : [],
    },
    {
        roomId : "room8",
        roomName : "reserve_room2",
        hostName : "seung",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 20,
        reserveUsers : ["kyo", "seo", "","","","","",""],
        isLive : false,
        channelNum : 0,
        liveUsers : [],
    },
    {
        roomId : "room9",
        roomName : "reserve_room3",
        hostName : "cho",
        hostCompany : "hostcompany",
        hostJob : "hostjob",
        reserveDate : "2021-03-19T18:00.00.000Z",
        reserveMax : 15,
        reserveUsers : ["kyo", "seo", "",""],
        isLive : false,
        channelNum : 0,
        liveUsers : [],
    }
]